#include "game.h"


GameLevel levels_data[] = {
  (GameLevel){
    .tiles = {
      {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_CORR, 0}, {TILE_CORR, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_NORM, 1}, {TILE_NORM, 1}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_CORR, 0}, {TILE_NORM, 0}, {TILE_NORM, 1}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 1}, {TILE_NORM, 0}, {TILE_CORR, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, 
    },
    .playerX = 7,
    .playerY = 5,
    .requiredBoxesCount = 4,
    .name = "First"
  },
  (GameLevel){
  },
};

// level template
#if 0
      {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_NORM, 0}, {TILE_WALL, 0}, 
      {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, {TILE_WALL, 0}, 
#endif
